baseURL = 'https://foreboo.github.io/blog/'
languageCode = 'en-us'
title = 'NiceDay'
publishDir = 'docs'

theme = "skyblue"

[taxonomies]
    category = "categories"
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true